### ISSUE TITLE
Add SPARQL as a dependency

### ISSUE THREAD

**Issue by jsphdms** [jsphdms/scotgov#18]

**Comment by GordonBryden** [comment]
I think I've fixed the dependency issues we were having with SPARQL. After looking into the source code of SPARQL, it looks like they were using library() to load in their required functions. This meant that our code wasn't loading in the required dependencies for SPARQL.

I've added SPARQL's dependencies to our DESCRIPTION page. I've run a few tests, and this seems to work.
