### ISSUE TITLE
Add a new function to return SPARQL queries as strings

### ISSUE THREAD

**Issue by jsphdms** [jsphdms/scotgov#42]
Input would be the same as `scotgov_get()` and output would be the corresponding SPARQL query.

**Comment by jsphdms** [comment]
After chatting with @GordonBryden the simplest approach would probably be to pull the relevant code out of scotgov_get() into a separate function. So scotgov_get() would call this new function to create the query. I'd welcome opinions on whether this new function should be internal or external

**Comment by GordonBryden** [comment]
get_dataset_query() now committed. It's a simple gutting of scotgov_get, returning the SPARQL query as a string. Scotgov_get now passes it's arguments to get_dataset_query, which it then passes to SPARQL.
