### ISSUE TITLE
Document the package

### ISSUE THREAD

**Issue by jsphdms** [jsphdms/scotgov#5]
E.g.
- readme
- download instructions
- roxygen2
- pkgdown
- Hide internal functions

**Comment by GordonBryden** [comment]
It looks like the internal functions are already hidden, unless they are explicitly mentioned in NAMESPACE.

**Comment by jsphdms** [comment]
OK I'll close this - everything on the list is done apart from pkgdown which in my opinion is a 'nice to have' at this stage.
